In [2]:
import torch

In [4]:
import numpy

In [3]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [5]:
a = numpy.array([1, 2, 3])

In [6]:
t = torch.from_numpy(a)

In [7]:
a

array([1, 2, 3])

In [8]:
t

tensor([1, 2, 3])

In [9]:
a[0]

1

In [10]:
t[0]

tensor(1)

In [11]:
t[0]=-1

In [12]:
t

tensor([-1,  2,  3])

In [13]:
a

array([-1,  2,  3])

In [14]:
b=torch.linspace(3, 10, steps=5)

In [15]:
b

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [16]:
b=torch.linspace(3, 10)

In [17]:
b

tensor([ 3.0000,  3.0707,  3.1414,  3.2121,  3.2828,  3.3535,  3.4242,  3.4949,
         3.5657,  3.6364,  3.7071,  3.7778,  3.8485,  3.9192,  3.9899,  4.0606,
         4.1313,  4.2020,  4.2727,  4.3434,  4.4141,  4.4848,  4.5556,  4.6263,
         4.6970,  4.7677,  4.8384,  4.9091,  4.9798,  5.0505,  5.1212,  5.1919,
         5.2626,  5.3333,  5.4040,  5.4747,  5.5455,  5.6162,  5.6869,  5.7576,
         5.8283,  5.8990,  5.9697,  6.0404,  6.1111,  6.1818,  6.2525,  6.3232,
         6.3939,  6.4646,  6.5354,  6.6061,  6.6768,  6.7475,  6.8182,  6.8889,
         6.9596,  7.0303,  7.1010,  7.1717,  7.2424,  7.3131,  7.3838,  7.4545,
         7.5253,  7.5960,  7.6667,  7.7374,  7.8081,  7.8788,  7.9495,  8.0202,
         8.0909,  8.1616,  8.2323,  8.3030,  8.3737,  8.4444,  8.5152,  8.5859,
         8.6566,  8.7273,  8.7980,  8.8687,  8.9394,  9.0101,  9.0808,  9.1515,
         9.2222,  9.2929,  9.3636,  9.4343,  9.5051,  9.5758,  9.6465,  9.7172,
         9.7879,  9.8586,  9.9293, 10.00

In [18]:
b=torch.linspace(3, 10,steps=10,out=c)

NameError: name 'c' is not defined

In [19]:
c=torch.ones(10)

In [20]:
c

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
b=torch.linspace(3, 10,steps=10,out=c)

In [22]:
c

tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])

In [23]:
b

tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])

In [24]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
torch.rand(2,3)

tensor([[0.9235, 0.4549, 0.2635],
        [0.7714, 0.7135, 0.2565]])

In [26]:
torch.randperm(4)

tensor([1, 0, 2, 3])

In [27]:
torch.arange(1, 4)

tensor([1, 2, 3])

In [28]:
 x = torch.randn(2, 3)

In [29]:
x

tensor([[ 1.0121,  0.6437, -0.1999],
        [-0.5497,  1.5984, -0.3971]])

In [30]:
torch.cat((x,x))

tensor([[ 1.0121,  0.6437, -0.1999],
        [-0.5497,  1.5984, -0.3971],
        [ 1.0121,  0.6437, -0.1999],
        [-0.5497,  1.5984, -0.3971]])

In [31]:
torch.cat((x,x),1)

tensor([[ 1.0121,  0.6437, -0.1999,  1.0121,  0.6437, -0.1999],
        [-0.5497,  1.5984, -0.3971, -0.5497,  1.5984, -0.3971]])

In [32]:
torch.chunk(x,2)

(tensor([[ 1.0121,  0.6437, -0.1999]]), tensor([[-0.5497,  1.5984, -0.3971]]))

In [33]:
torch.chunk(x,3)

(tensor([[ 1.0121,  0.6437, -0.1999]]), tensor([[-0.5497,  1.5984, -0.3971]]))

In [35]:
torch.chunk(x,2,dim=1)

(tensor([[ 1.0121,  0.6437],
         [-0.5497,  1.5984]]), tensor([[-0.1999],
         [-0.3971]]))

In [36]:
x = torch.randn(5, 3)

In [37]:
torch.chunk(x,2)

(tensor([[ 0.4664,  0.8822, -0.5245],
         [ 0.0598,  0.3959,  0.8148],
         [ 0.4354, -0.9249,  0.6533]]), tensor([[-2.1596, -0.6189, -0.5041],
         [-1.0751, -0.0698,  0.3778]]))

In [38]:
torch.chunk(x,3)

(tensor([[ 0.4664,  0.8822, -0.5245],
         [ 0.0598,  0.3959,  0.8148]]), tensor([[ 0.4354, -0.9249,  0.6533],
         [-2.1596, -0.6189, -0.5041]]), tensor([[-1.0751, -0.0698,  0.3778]]))

In [39]:
t = torch.Tensor([[1,2],[3,4]])

In [40]:
t

tensor([[1., 2.],
        [3., 4.]])

In [42]:
 torch.gather(t, 1, torch.LongTensor([[0,0],[1,0]]))

tensor([[1., 1.],
        [4., 3.]])

In [43]:
x = torch.randn(3, 4)

In [44]:
indices = torch.LongTensor([0, 2])

In [45]:
indices

tensor([0, 2])

In [46]:
x = torch.randn(3, 4)

In [47]:
m = torch.zeros(3, 4)

In [48]:
m

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
m[1,3]=1

In [51]:
m[2,3]=1

In [54]:
m[1,2]=1

In [58]:
m=m.byte()

In [59]:
m

tensor([[0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 0, 1]], dtype=torch.uint8)

In [61]:
x

tensor([[-1.4236, -2.9457,  0.2037, -0.1936],
        [-1.0537,  0.7679,  0.4071,  0.2481],
        [ 1.1412, -0.0913, -0.1547, -2.2438]])

In [60]:
torch.masked_select(x,m)

tensor([ 0.4071,  0.2481, -2.2438])

In [63]:
torch.nonzero(m)

tensor([[1, 2],
        [1, 3],
        [2, 3]])

In [64]:
m

tensor([[0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 0, 1]], dtype=torch.uint8)

In [65]:
torch.initial_seed()

6123140745187411125

In [66]:
torch.get_num_threads()

1

In [69]:
torch.set_num_threads(4)

In [70]:
torch.get_num_threads()

1